type User {
  athleteId: Int!
  accessToken: String
  refreshToken: String
  expiresAt: Time
}

type Segment {
  segmentId: Int!
  counts: [Count!] @relation
}

type Count {
  ts: Time!
  segment: Segment!
  effortCount: Int!
  athleteCount: Int!
}

type Query {
  userById(athleteId: Int!): User!
  allSegments: [Segment!]
  segmentById(segmentId: Int!): Segment
}
